# services:
#   frontend:
#     build: ./AutoTranscriber
#     ports:
#       - "5173:5173"
#     volumes:
#       - ./AutoTranscriber:/app
#       - /app/node_modules
#     environment:
#       - VITE_API_URL=http://localhost:8000

services:
  frontend:
    build: ./AutoTranscriber
    ports:
      - "5173:5173"
    volumes:
      - ./AutoTranscriber:/app
      - /app/node_modules
    environment:
      # Changed from localhost to your host IP
      - VITE_API_URL=http://192.168.178.107:8000